name: ianmoffitt
recipe: lamp
config:
  php: '8.0'
  database: mysql:5.7
  webroot: docroot
  composer_version: '2.3.10'
  xdebug: debug
  config:
    php: config/php.ini

keys:
  - id_rsa

excludes:
  - vendor
  - node_modules
  - '!vendor/drush!'

events:
  pre-start:
    - appserver: composer install

services:
  database:
    type: mysql:5.7
    creds:
      database: drupal9
      user: drupal9
      password: drupal9
  node:
    type: node:14
  pma:
    type: phpmyadmin

tooling:
  drush:
    service: appserver
    cmd:
      - drush
  sync:
    service: appserver
    cmd:
      - drush sql:sync @self.prod @self --yes
  static:
    service: node
    cwd: /app/docroot/themes/custom/nth/_src
    cmd:
      - npm run server
  install:
    service: node
    cwd: /app/docroot/themes/custom/nth/_src
    cmd:
      - cd /app/docroot/themes/custom/nth/_src
      - npm install

