name: ianmoffitt
recipe: lamp
config:
  php: '8.1'
  database: mysql:5.7
  webroot: docroot
  composer_version: '2.3.10'
  xdebug: debug
  config:
    php: config/php.ini

services:
  database:
    type: mysql:5.7
    creds:
      database: drupal9
      user: drupal9
      password: drupal9
  node:
    type: node:14
  pma:
    type: phpmyadmin

tooling:
  drush:
    service: appserver
    cmd:
      - drush
  pull:
    service: appserver
    cmd:
      - drush sql:sync @self.prod @self --yes
  static:
    service: node
    cwd: /app/docroot/themes/custom/nth/_src
    cmd:
      - npm run server
