_core:
  default_config_hash: _QWheLY4erYyAlt1vdLtxMirLer05mMexNbeoNJd_As
status: true
mapping:
  type: simple
  conditions:
    not:
      extensions:
        - css
        - js
  domain: ianmoffitt.ddev.site
scheme: //
farfuture:
  status: true
stream_wrappers:
  - public
