_core:
  default_config_hash: FGYrMvt5Li0Jm92wyoGSiFFNoI_WqcHTeNDMq4jHId0
langcode: en
status: true
mapping:
  type: simple
  conditions:
    not:
      extensions:
        - css
        - js
  domain: ianmoffitt.ddev.site
scheme: //
farfuture:
  status: true
stream_wrappers:
  - public
