_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  auto_entitylabel: 0
  automated_cron: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor5: 0
  comment: 0
  config: 0
  content_moderation: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  disqus: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  entity_usage: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  gin_login: 0
  gin_toolbar: 0
  help: 0
  image: 0
  inline_form_errors: 0
  layout_discovery: 0
  link: 0
  link_attributes: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  node: 0
  nth_helper: 0
  nth_twitter_block: 0
  options: 0
  page_cache: 0
  paragraphs_library: 0
  path: 0
  path_alias: 0
  phpass: 0
  redirect: 0
  redirect_404: 0
  responsive_image: 0
  sdc: 0
  serialization: 0
  settings_tray: 0
  shortcut: 0
  simple_sitemap: 0
  smart_trim: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  twig_tweak: 0
  update: 0
  upgrade_status: 0
  user: 0
  views_conditional: 0
  views_ui: 0
  workflows: 0
  pathauto: 1
  views: 10
  paragraphs: 11
  ian: 1000
theme:
  stable: 0
  nth: 0
  claro: 0
  gin: 0
profile: ian
