_core:
  default_config_hash: nRysvGldi9bVjwAPJlKXm9C8exWIT4hQhVYJPgYTCWI
favicon:
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: false
logo:
  use_default: true
third_party_settings:
  shortcut:
    module_link: true
preset_accent_color: custom
preset_focus_color: gin
enable_darkmode: '0'
classic_toolbar: vertical
secondary_toolbar_frontend: true
high_contrast_mode: false
accent_color: '#00665c'
focus_color: ''
show_description_toggle: false
show_user_theme_settings: false
