_core:
  default_config_hash: 0bH7DQmxEhBEEh_Dutc7X92yWruM_iYBmy-0igQ5jbg
scheme_allow_list:
  - http
  - https
  - files
  - internal
protocol_style: full
local_paths: "https://ianmoffitt.ddev.site/\r\nhttps://cms.ianmoffitt.dev/\r\nhttps://ianmoffitt.dev/"
keep_language_prefix: null
