_core:
  default_config_hash: fnphwmCgfLAWN43jxKXNonjNol1VQ74yF2JJKrmEdSg
langcode: en
uuid: 2e26a803-0f1e-4b70-b597-025bc06b2684
name: ianmoffitt.dev
mail: cms@ianmoffitt.dev
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
