_core:
  default_config_hash: l58O_yEXSo-SeJi19LXdzTU1tNJG3lmnIhCitRkM1tk
langcode: en
uuid: 2e26a803-0f1e-4b70-b597-025bc06b2684
name: IanMoffitt.dev
mail: dev@ianmoffitt.dev
slogan: ''
page:
  403: ''
  404: ''
  front: /user/login
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
