_core:
  default_config_hash: 5GpDpDMoMHbJhhjah60rbrqZ2YvZaNFzyr-02CBr9-4
first_day: 0
country:
  default: US
timezone:
  default: America/New_York
  user:
    configurable: false
    default: 0
    warn: false
