_core:
  default_config_hash: prq8GGIB4GmZHFqCiqumrycqgdEEpexh50L-gLfuQkg
check:
  disabled_extensions: false
  interval_days: 7
fetch:
  url: ''
  max_attempts: 2
  timeout: 30
notification:
  emails:
    - siteadmin@ianmoffitt.dev
  threshold: security
