name: Deploy Development

on:
  push:
    branches-ignore:
      - main
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan -T 45 -H ${{ secrets.IP }} >> ~/.ssh/known_hosts

  prepare:
    runs-on: ubuntu-latest

    needs: ssh

    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        run: |
          ssh ${{ secrets.USER_IP }} "bash -s ${{ github.sha }}" < scripts/prepare.sh

  build:
    runs-on: ubuntu-latest

    needs: [ssh, prepare]

    steps:
      - name: Build
        run: |
          ssh ${{ secrets.USER_IP }} "cd /var/www/dev.ianmoffitt.dev && /usr/bin/bash scripts/dev.sh"
