name: Deploy Development

on:
  push:
    branches:
      - main
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/production.key
          chmod 600 ~/.ssh/production.key
          cat >>~/.ssh/config <<END
          Host production
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/production.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ian
          SSH_KEY: ${{ secrets.SSH_PRIV_KEY }}
          SSH_HOST: ${{ secrets.IP }}
      - name: Update Repository to Latest
        run: >
          ssh production "          
            cd /var/www/ianmoffitt.dev
          
            git fetch origin --depth=5
            git clean -df
            git reset --hard
            git pull
          
            bash scripts/prod.sh
          "

  npminstall:
    needs: update
    runs-on: ubuntu-latest

    steps:
      - name: SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/production.key
          chmod 600 ~/.ssh/production.key
          cat >>~/.ssh/config <<END
          Host production
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/production.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ian
          SSH_KEY: ${{ secrets.SSH_PRIV_KEY }}
          SSH_HOST: ${{ secrets.IP }}
      - name: NPM Install
        run: > 
          ssh production "
            cd /var/www/ianmoffitt.dev
            npm install --omit=dev
          "

  composerinstall:
    needs: update
    runs-on: ubuntu-latest

    steps:
      - name: SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/production.key
          chmod 600 ~/.ssh/production.key
          cat >>~/.ssh/config <<END
          Host production
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/production.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ian
          SSH_KEY: ${{ secrets.SSH_PRIV_KEY }}
          SSH_HOST: ${{ secrets.IP }}
      - name: Composer Install
        run: >
          ssh production "
            cd /var/www/ianmoffitt.dev
            composer install -q
          "

  drupaldeploy:
    needs: composerinstall
    runs-on: ubuntu-latest

    steps:
      - name: SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/production.key
          chmod 600 ~/.ssh/production.key
          cat >>~/.ssh/config <<END
          Host production
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/production.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ian
          SSH_KEY: ${{ secrets.SSH_PRIV_KEY }}
          SSH_HOST: ${{ secrets.IP }}
      - name: Drush Deploy
        run: >
          ssh production "
            cd /var/www/ianmoffitt.dev
            drush deploy
          "

  eleventybuild:
    needs: [npminstall, drupaldeploy]
    runs-on: ubuntu-latest

    steps:
      - name: SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/production.key
          chmod 600 ~/.ssh/production.key
          cat >>~/.ssh/config <<END
          Host production
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/production.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ian
          SSH_KEY: ${{ secrets.SSH_PRIV_KEY }}
          SSH_HOST: ${{ secrets.IP }}
      - name: Build 11ty Site
        run: >
          ssh production "
            cd /var/www/ianmoffitt.dev
            npm run prod
          "