name: Deploy Development

on:
  push:
    branches-ignore:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/

      - name: SSH 2
        run: |
          echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/id_rsa.pub

      - name: SSH 3
        run: |
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub

      - name: Test out SSH connection
        run: |
          ssh ${{ secrets.USER_IP }} "cd /var/www/dev.ianmoffitt.dev; git fetch origin; git checkout ${{ github.sha }}; sh scripts/dev.sh;"
          
        
    


