name: Test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup DDEV
        uses: ddev/github-action-setup-ddev@v1

      - run: ddev describe

      - run: ddev composer install
      - run: ddev npm install

      - run: ddev pull drush -y

      - run: npm run serve &

      - run: npm test
