name: Test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: SSH
        run: |
          mkdir -p .ddev/homeadditions/.ssh
          echo "${{ secrets.SSH_PRIV_KEY }}" > .ddev/homeadditions/.ssh/id_rsa
          chmod 700 .ddev/homeadditions/.ssh
          chmod 600 .ddev/homeadditions/.ssh/id_rsa

      - name: Setup DDEV
        uses: ddev/github-action-setup-ddev@v1

      - run: ddev describe

      - run: ddev auth ssh

      - run: ddev composer install
      - run: ddev npm install

      - run: ddev pull drush -y

      - run: npm run serve &

      - run: npm test
