name: Test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat >>~/.ssh/config <<END
          Host production
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END
          
          mkdir -p .ddev/homeadditions/.ssh
          echo "$SSH_KEY" > .ddev/homeadditions/.ssh/id_rsa
          chmod 700 .ddev/homeadditions/.ssh
          chmod 600 .ddev/homeadditions/.ssh/id_rsa
        env:
          SSH_USER: ian
          SSH_KEY: ${{ secrets.SSH_PRIV_KEY }}
          SSH_HOST: ${{ secrets.IP }}

      - name: Set up host keys
        run: |
          mkdir -p ~/.ssh-agent/           
          echo "${{ secrets.IP }}" > .ddev/homeadditions/.ssh/known_hosts
          chmod 600 .ddev/homeadditions/.ssh/known_hosts   

      - name: Setup DDEV
        uses: ddev/github-action-setup-ddev@v1

      - run: ddev describe

      - run: ddev composer install

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Cache Cypress Binary
        id: cache-cypress-binary
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: binary-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: ddev npm ci

      - run: ddev pull drush -y

      - run: ddev npm run serve &

      - run: ddev cypress-run e2e/drupal.cy.js,e2e/drupal-authenticated.cy.js --config baseUrl=https://ianmoffitt.ddev.site
      - run: ddev cypress-run e2e/eleventy.cy.js --config baseUrl=https://localhost:8080
