name: Test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat >>~/.ssh/config <<END
          Host production
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ian
          SSH_KEY: ${{ secrets.SSH_PRIV_KEY }}
          SSH_HOST: ${{ secrets.IP }}

      - name: Set up host keys
        run: |
          echo "${{ secrets.IP }}" > .ddev/homeadditions/.ssh/known_hosts
          echo "${{ secrets.IP }}" > ~/.ssh/known_hosts
      - name: Setup DDEV
        uses: ddev/github-action-setup-ddev@v1

      - run: ddev describe

      - run: ddev composer install
      - run: ddev npm install

      - run: ddev pull drush -y

      - run: |
          npm install cypress -g
          cypress install

      - run: npm run serve &

      - run: npm test
